<h1>Post Add</h1>
<?php $form->prepare(); ?>

<?php if ($this->flashMessenger()->getSuccessMessages()): ?>
    <?php foreach ($this->flashMessenger()->getSuccessMessages() as $message) ?>
        <div class="alert alert-success">
    <?= $message ?>
    </div>
<?php endif ?>

<?php echo $this->form()->openTag($form); ?>
<?php echo $this->formHidden($form->get('id')); ?>
<?php echo $this->formRow($form->get('title')); ?>
<br/>
<?php echo $this->formRow($form->get('description')); ?>
<br/>
<?php echo $this->formRow($form->get('category')); ?>
<br/>
<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>
